version: "3.9"
services:

  ##Database config
  mysql:
    image: mysql:8.0.31
    ports:
      - "8803:3306"
    environment:
      - MYSQL_DATABASE=chatservice
      - MYSQL_ROOT_PASSWORD=123456
    profiles:
      - db
      - mysql
    volumes:
      - .db/mysql:/var/lib/mysql